default: &DEFAULT
  adapter: mysql2
  encoding: utf8
  min_messages: warning

  host: <%=ENV['db_host'] %>
  database: <%=ENV['db_db']%>
  username: <%=ENV['db_username']%>
  password: <%=ENV['db_password']%>

development:
  <<: *DEFAULT

production:
  <<: *DEFAULT

test:
  <<: *DEFAULT
